config/routes.rb
Rails.application.routes.draw do
  root :to => "pages#home"
  get "/landing" => "pages#landing", :as => "landing"
  get "/users" => "pages#users", :as => "users"

  resources :players, :except => [:destroy]
  get "/players/:id/add_profile" => "players#add_profile", :as => "player_add_profile"
  patch "/players/:id/add_profile" => "players#profile_update", :as => "player_update_profile"
  post "/players/:id/add_profile" => "players#profile_update"

  resources :teams, :except => [:destroy]
  get "/teams/:id/add_profile" => "teams#add_profile", :as => "team_add_profile"
  patch "/teams/:id/add_profile" => "teams#profile_update", :as => "team_update_profile"
  get "/teams/join/:id" => "teams#join", :as => "join_team"
  get "/teams/leave/:id" => "teams#leave", :as => "leave_team"

  resources :grounds
  resources :games, :except => [:destroy]

  get "/login" => "session#new"
  post "/login" => "session#create"
  delete "/login" => "session#destroy"
  get "/auth/google_oauth2/callback" => "session#omniauth"
end

app/models/ground.rb
class Ground < ApplicationRecord
    has_many :games
end

app/controllers/grounds_controller.rb
class GroundsController < ApplicationController
  before_action :check_for_admin, :only => [:new, :edit]
  
  def index
    @grounds = Ground.all
  end
  
  def new
    @ground = Ground.new
  end

  def edit
    @ground = Ground.find params[:id]
  end 

  def show
    @ground = Ground.find params[:id]
  end 

  def create
    ground = Ground.new ground_params
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      ground.image = req["public_id"]
    end
    if ground.save
      redirect_to grounds_path
    else
      render :new
    end
  end

  def update
    ground = Ground.find params[:id]
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      ground.image = req["public_id"]
    end
    ground.update_attributes ground_params
    if ground.save
      redirect_to grounds_path
    else
      render :new
    end
  end 

  def destroy
    ground = Ground.find params[:id]
    ground.destroy
    redirect_to grounds_path
  end

  private
  def ground_params
    params.require(:ground).permit(:name, :address, :image, :google_map)
  end


end

app/helpers/grounds_helper.rb
module GroundsHelper
end

app/views/grounds/_form.html.erb
<%= form_for @ground, :html => {:multipart => true} do |f| %>
  
  <%= f.label :name, "Ground Name" %>
  <%= f.text_field :name %>

  <%= f.label :address %>
  <%= f.text_field :address %>
  
  <%= f.label :image, "Ground Image" %>
  <%= f.cl_image_upload :image %>
  
  <%= f.label :google_map %>
  <%= f.text_field :google_map %>

  <%= f.submit %>
<% end %>

app/views/grounds/edit.html.erb
<h1>Edit Ground</h1>

<%= render 'grounds/form' %>

app/views/grounds/index.html.erb
<h1>All Grounds</h1>

<% @grounds.each do |ground| %>
  <%= link_to ground.name, ground_path(ground) %>
  <%= cl_image_tag(ground.image) %>
  <% if @current_user.admin? %>
    <p><%= link_to("Edit Ground", edit_ground_path(ground)) %></p>
    <%= button_to 'Delete Ground', ground, :method => 'delete' %>
  <% end %>
<% end %>

app/views/grounds/new.html.erb
<h1>Add a new ground</h1>

<%= render 'grounds/form' %>

app/views/grounds/show.html.erb
<h1><%= @ground.name %></h1>
<%= cl_image_tag(@ground.image) %>
<%= @ground.address %>
<%= @ground.google_map %>


<% if @current_user.admin? %>
    <p><%= link_to("Edit Ground", edit_ground_path(@ground)) %></p>
    <%= button_to 'Delete Ground', ground, :method => 'delete' %>
<% end %>