config/routes.rb
Rails.application.routes.draw do
  root :to => "pages#home"
  get "/landing" => "pages#landing", :as => "landing"
  get "/users" => "pages#users", :as => "users"

  resources :players, :except => [:destroy]
  get "/players/:id/add_profile" => "players#add_profile", :as => "player_add_profile"
  patch "/players/:id/add_profile" => "players#profile_update", :as => "player_update_profile"
  post "/players/:id/add_profile" => "players#profile_update"

  resources :teams, :except => [:destroy]
  get "/teams/:id/add_profile" => "teams#add_profile", :as => "team_add_profile"
  patch "/teams/:id/add_profile" => "teams#profile_update", :as => "team_update_profile"
  get "/teams/join/:id" => "teams#join", :as => "join_team"
  get "/teams/leave/:id" => "teams#leave", :as => "leave_team"

  resources :grounds
  resources :games, :except => [:destroy]

  get "/login" => "session#new"
  post "/login" => "session#create"
  delete "/login" => "session#destroy"
  get "/auth/google_oauth2/callback" => "session#omniauth"
end

app/models/player.rb
class Player < ApplicationRecord
    belongs_to :team, :optional => true
    has_secure_password 
    
    validates :email, :uniqueness => true, :presence => true
    validates :password, length: { in: 7..20}

    #Create a user from Google OmniAuth
    def self.create_from_omniauth(auth)
        player = Player.find_or_create_by(uid: auth['uid'], provider: auth["provider"]) do |p|
        p.email = auth['info']['email']
        p.first_name = auth['info']['first_name']
        p.last_name = auth['info']['last_name']
        p.password = SecureRandom.hex(16)
        end
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :check_for_player, :only => [:edit]
  
  def index
    @players = Player.all.order("created_at DESC")
  end

  def add_profile
    @player = Player.find params[:id]
  end

  def profile_update
    player = Player.find params[:id]
    if params[:player][:profile].present?
      profile = Cloudinary::Uploader.upload(params[:player][:profile])
      player.profile = profile["public_id"]
      
    end

    if params[:player][:banner].present?
      banner = Cloudinary::Uploader.upload(params[:player][:banner])
      player.banner = banner["public_id"]
    end

    player.update_attributes(add_profile_params)
    player.save
    if player.save
      session[:user_id] = player.id
      redirect_to root_path
    else 
      render :add_profile
    end 
  end 

  def new 
    @player = Player.new
  end

  def create
    @player = Player.create(player_params)
    if @player.save
      redirect_to player_add_profile_path(@player)
    else 
      render :new
    end 
  end

  def edit 
    @player = Player.find params[:id]
  end 

  def show
    @player = Player.find params[:id]
  end 

  def update
    player = Player.find params[:id] 
    player.update add_profile_params
    redirect_to player_path(player)
  end

  private
  def player_params
    params.require(:player).permit(:email, :password, :password_confirmation)
  end

  def add_profile_params
    params.require(:player).permit(:first_name, :last_name, :role, :grade, :suburb, :bio)
  end 

end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for @player do |f| %>
  
  
    <%= f.label :first_name, "First Name", :autofocus => true, :required => true %>
    <%= f.text_field :first_name %>
    
    <%= f.label :last_name, "Last Name", :required => true %>
    <%= f.text_field :last_name %>


  <%= f.label :grade %>
  <%= f.select(:grade, ["A", "B", "C", "D"], :include_blank => true, :required => true)%>
  
  <%= f.label :role %>
  <%= f.select(:role, ["Top Order Batsman", "Middle Order Batsman", "All Rounder", "Medium Pace Bowler", "Pace Bowler", "Fast Bowler", "Leg Spin Bowler", "Off Spin Bowler", "There for the tins", "Bat 11, don't bowl, terrible umpire", "Bantsmaster"], :include_blank => true, :required => true)%>

  <%= f.label :suburb %>
  <%= f.number_field :suburb, :placeholder => "ie. 2066", :max => 5000, :min => 0 %>
  
  <%#f.label(:profile_image, "Profile Image")  %>
  <%# f.cl_image_tag(:profile_image) %>

  <%# f.label(:logo, "Banner Photo")  %>
  <%# f.cl_image_tag(:banner_photo) %>

<%= f.submit("Update Profile") %>
<% end %>

app/views/players/add_profile.html.erb
<head>
  <title> Create Your Profile | Syd Cricket </title>
</head>

<div class="container full-height">

  <div class="sign-up">
    <h1>Create Profile</h1>
    <% if @player.errors.any? %>
    <% @player.errors.full_messages.each do |msg| %>
    <div class="errors u-full-width center">
      <ol>
        <li><%= msg %></li>
      </ol>
    </div>
    <% end %>
    <% end %>

    <%= form_for @player, url: player_update_profile_path(@player), :class => "u-full-width", :html => {:multipart => true} do |f| %>
    <div class="row">
      <div class="six columns">
        <%= f.label :first_name, "First Name", :autofocus => true, :required => true %>
        <%= f.text_field :first_name, :class => "u-full-width"  %>
      </div>
      <div class="six columns">
        <%= f.label :last_name, "Last Name", :required => true %>
        <%= f.text_field :last_name, :class => "u-full-width" %>
      </div>
    </div>
    <div class="row">
      <div class="four columns">
        <%= f.label :grade %>
        <%= f.select(:grade, ["A", "B", "C", "D"], :include_blank => true, :required => true, :class => "")%>
      </div>
      <div class="four columns">
        <%= f.label :suburb %>
        <%= f.number_field :suburb, :placeholder => "Suburb (ie. 2066)", :class => "" %>
      </div>
      <div class="four columns">
        <%= f.label :role %>
        <%= f.select(:role, ["Top Order Batsman", "Middle Order Batsman", "All Rounder", "Medium Pace Bowler", "Pace Bowler", "Fast Bowler", "Leg Spin Bowler", "Off Spin Bowler", "There for the tins", "Bat 11, don't bowl, terrible umpire", "Bantsmaster"], :include_blank => true, :required => true, :class => "u-mid-width")%>
      </div>
    </div>
    <div class="row">
      <%= f.label :bio %>
      <%= f.text_area(:bio, :cols => 10, :rows => 10, :class => "u-full-width") %>
    </div>
    <div class="row">
      <div class="six columns">
        <%= f.label :profile, "Profile Photo" %>
        <%= f.file_field :profile, :class => "u-full-width" %>
      </div>
      <div class="six columns">
        <%= f.label :banner, "Banner Photo" %>
        <%= f.file_field :banner, :class => "u-full-width" %>
      </div>
    </div>
    <%= f.submit("Register", :class => "gold u-full-width") %>
    <% end %>
  </div>
</div>
<div class="wicket">
  <%= image_tag "wicket.svg" %>
</div>

app/views/players/edit.html.erb
<h1>Edit Player <%= @player.first_name %> <%= @player.last_name %></h1>

<%= render 'players/form' %>

app/views/players/index.html.erb
<div class="container index-template">
  <div class="row">
    <section class="side-menu">
        <h1>Players</h1>
        <ul class="menu">
          <li class="menu-item"><%= link_to "Go Home", root_path %></li>
          <li class="menu-item"><%= link_to "Games", games_path %></li>
          <li class="menu-item"><%= link_to "Teams", games_path %></li>
        </ul>
    </section>

    <% @players.each do |player| %>
      <div class="profile-card">
        <div class="row">
          <div class="three columns">
            <%= cl_image_tag(player.profile, :class => "profile-image") %>
          </div>
          <div class="nine columns">
            <span class="title"><%= player.first_name %> <%= player.last_name %></span>
            <% if player.team_id.nil?  %>
              <p>Looking for a team!</p>
            <% end %>
            <p>Grade:<%= player.grade %></p>
            <p class="bio"><%= truncate player.bio, :length => 120 %></p>
            <%= link_to("View Profile", player_path(player), :class => "cta-btn red") %>
          </div>
        </div>    
      </div>
    <% end %>
  </div>
</div>


   
            

app/views/players/new.html.erb
<head>
  <title> Player Sign Up | Syd Cricket </title>
</head>

<div class="container center full-height">
  
  <div class="sign-up">
    <h1>Player Sign Up</h1>
    <% if @player.errors.any? %>
    <% @player.errors.full_messages.each do |msg| %>
    <div class="errors u-mid-width center">
      <ol>
        <li><%= msg %></li>
      </ol>
    </div>
    <% end %>
    <% end %>

    <%= form_for(@player, :class => "u-mid-width", :html => { :multipart => true }) do |f| %>
  
        <%= f.label :email, :hidden => true %>
        <%= f.email_field :email, :placeholder => "Email Address", :class => "u-mid-width" %>
   
        <%= f.label :password, :hidden => true %>
        <%= f.password_field :password, :placeholder => "Password (6 to 20 characters)", :class => "u-mid-width" %>
        <br>
    
        <%= f.label :password_confirmation, :hidden => true %>
        <%= f.password_field :password_confirmation, :placeholder => "Confirm your password", :class => "u-mid-width" %>
   
      <%= f.submit("Get Started", :class => "gold u-full-width") %>
    <% end %>
    
    <%= button_to "/auth/google_oauth2", :id => "google-btn", :class => "button grey" do %> 
      <i id="g-icon" class="fa fa-google"></i>
    <% end %>
  </div>
</div>

<div class="wicket">
  <%= image_tag "wicket.svg" %>
</div>

app/views/players/show.html.erb
<head>
  <title><%= @player.first_name %> <%= @player.last_name %> | SydCricket</title>
</head>


<div class="row image-banner">
  <%= cl_image_tag(@player.banner) %>
</div>


<div class="container profile">
  <div class="three columns">
    <div class="profile-info">
      <%= cl_image_tag(@player.profile, :class => "profile-image") %>
      <h1><%= @player.first_name %> <%= @player.last_name %></h1>
      <p><%= @player.bio %></p>
      <p>Role: <%= @player.role %></p>
      <p>Grade: <%= @player.grade %></p>

      <% if @current_user.id == params[:id].to_i %>
        <%= link_to("Edit your profile", edit_player_path(@player), :class=>"cta-btn") %>
        <% unless @player.team.nil? %>
          <%= link_to("Leave Team", leave_team_path(@player.team), :class=>"cta-btn grey") %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="nine columns">
    <div class="profile-section">
      <span>Testy test</span>
      <% unless @player.team.nil? %>
        <h2><%= @player.team.name %></h2>
      <% end %>
    </div>

  </div>
</div>






<% unless @player.team.nil? %>
<p><%= @player.team.name %></p>

<!--Player-->
<ul>
  <% @player.team.players.each do |player| %>
  <li><%= player.first_name %> <%= player.last_name %></li>
  <% end %>
</ul>

<!--Games-->
<p>Games</p>
<ul>
  <% if @player.team.games.present? %>
  <% @player.team.games.each do |game| %>
  <li><%= game.team1.name %> vs <%= game.team2.name %></li>
  <% end %>
  <% end  %>
</ul>
<% end %>