config/routes.rb
Rails.application.routes.draw do
  root :to => "pages#home"
  get "/landing" => "pages#landing", :as => "landing"
  get "/users" => "pages#users", :as => "users"

  resources :players, :except => [:destroy]
  get "/players/:id/add_profile" => "players#add_profile", :as => "player_add_profile"
  patch "/players/:id/add_profile" => "players#profile_update", :as => "player_update_profile"
  post "/players/:id/add_profile" => "players#profile_update"

  resources :teams, :except => [:destroy]
  get "/teams/:id/add_profile" => "teams#add_profile", :as => "team_add_profile"
  patch "/teams/:id/add_profile" => "teams#profile_update", :as => "team_update_profile"
  get "/teams/join/:id" => "teams#join", :as => "join_team"
  get "/teams/leave/:id" => "teams#leave", :as => "leave_team"

  resources :grounds
  resources :games, :except => [:destroy]

  get "/login" => "session#new"
  post "/login" => "session#create"
  delete "/login" => "session#destroy"
  get "/auth/google_oauth2/callback" => "session#omniauth"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= favicon_link_tag %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css"
    integrity="sha384-vSIIfh2YWi9wW0r9iZe7RJPrKwp6bG+s9QZMoITbCckVJqGCCRhc+ccxNcdpHuYu" crossorigin="anonymous">
  <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
  <%= javascript_include_tag "application", 'data-turbolinks-track': "reload" %>
  <%= cloudinary_js_config %>
  <script>
    $(document).ready(function () {
      //Open Nav
      $("#menu").on("click", function () {
        $(".nav-overlay").toggleClass("visible");
      });
      //Close Nav
      $(".closebtn").on("click", function () {
        $(".nav-overlay").toggleClass("visible");
      });
    });
  </script>
</head>
<body>
<% unless controller_name == "pages" && ["landing"].include?(action_name) || controller_name == "player" && ["new"].include?(action_name) %>
  <nav class="nav">
    <!--Logo -->
    <%= link_to root_path do %>
      <%= image_tag("logo.svg", :class => "nav-logo") %>
    <% end %>

    <!-- Nav Overlay -->  
      <div class="nav-overlay">
        <a href="javascript:void(0)" class="closebtn">×</a> 
        <div class="nav-overlay-content">
          <div class="menu-wrapper">
            <%= link_to "Teams", teams_path %>
            <%= link_to "Players", players_path %>
            <%= link_to "Grounds", grounds_path %>
            <%= link_to "Games", games_path %>
            <% if @current_user.present? %>
              <!-- Admin -->
              <% if @current_user.admin? %>
                <%= link_to "Create a ground", new_ground_path, :class => "red-text" %>
                <%= link_to "Users", users_path, :class => "red-text" %>
              <% end %>
              <% if @current_user.user_role == "team" %>
                <%= link_to("Create a game", new_game_path, :class => "red-text") %>
              <% end %>
              <% if @current_user.user_role == "player" %>
                <%= link_to("Join a team", teams_path, :class => "red-text") %>
                <%= link_to("View profile", players_path(@current_user), :class => "red-text") %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
  <!-- ICONS -->
  <ul class="icons">
    <% unless @current_user.present? %>
    <li><%= link_to "Join", new_player_path, :class=>"cta-btn" %></li>
    <li><%= link_to "New Team", new_team_path, :class=>"cta-btn" %></li>
    <% end  %>
    <li><a id="menu"><i class="far fa-compass"></i></a></li>
    <% if @current_user.present? %>
      <!--Change Player/Team routes for user profiles-->    
      <% if @current_user.user_role == "team" %>
          <li>
            <%= link_to team_path(@current_user) do %>
              <i class="far fa-user-circle"></i>
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to player_path(@current_user) do %>
              <i class="far fa-user-circle"></i>
            <% end %>
          </li>
      <% end %>
      <!--Change Login/Logout-->    
      <li>
        <%= link_to login_path, :method => "delete" do %>
          <i class="fas fa-sign-out-alt"></i>
        <% end %>          
      </li>
      <% else %>
      <li>
        <%= link_to login_path do %>
          <i class="fas fa-sign-in-alt"></i>
        <% end %>
      </li>
    <% end %>
  </ul> 
  </nav>
<% end %>



  <%= yield %>

</body>

</html>